version: "3.8"

services:
  app:
    image: tikhoplav/go
    working_dir: /src
    volumes:
      - ./src:/src
      - ./pkg:/go/pkg
    environment:
      - DB_URL=postgres://dev:dev@db:5432/dev

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=dev
      - POSTGRES_DB=dev
